#!/bin/bash

set -ex

_prefix=$PWD/llvm-install/
source config.sh

/usr/bin/cmake \
    -S ../llvm \
    -B llvm-build \
    -G Ninja \
    -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG \
    -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG \
    -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
    -DCMAKE_INSTALL_PREFIX:PATH=${_prefix} \
    -DINCLUDE_INSTALL_DIR:PATH=${_includedir} \
    -DLIB_INSTALL_DIR:PATH=${_libdir} \
    -DSYSCONF_INSTALL_DIR:PATH=${_sysconfdir} \
    -DSHARE_INSTALL_PREFIX:PATH=${_datarootdir} \
    -DLIB_SUFFIX=64 \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DLLVM_PARALLEL_LINK_JOBS=1 \
    -DCMAKE_BUILD_TYPE=${build_type} \
    -DCMAKE_SKIP_RPATH:BOOL=ON \
    -DLLVM_LIBDIR_SUFFIX=64 \
    -DLLVM_TARGETS_TO_BUILD=all \
    -DLLVM_ENABLE_LIBCXX:BOOL=OFF \
    -DLLVM_ENABLE_ZLIB:BOOL=ON \
    -DLLVM_ENABLE_FFI:BOOL=ON \
    -DLLVM_ENABLE_RTTI:BOOL=ON \
    -DLLVM_USE_PERF:BOOL=ON \
    -DLLVM_BINUTILS_INCDIR=${_includedir} \
    -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR \
    -DLLVM_BUILD_RUNTIME:BOOL=ON \
    -DLLVM_INCLUDE_TOOLS:BOOL=ON \
    -DLLVM_BUILD_TOOLS:BOOL=ON \
    -DLLVM_INCLUDE_TESTS:BOOL=ON \
    -DLLVM_BUILD_TESTS:BOOL=ON \
    -DLLVM_LIT_EXTRA_ARGS=-v \
    -DLLVM_INCLUDE_EXAMPLES:BOOL=ON \
    -DLLVM_BUILD_EXAMPLES:BOOL=OFF \
    -DLLVM_INCLUDE_UTILS:BOOL=ON \
    -DLLVM_INSTALL_UTILS:BOOL=ON \
    -DLLVM_UTILS_INSTALL_DIR:PATH=${_bindir} \
    -DLLVM_TOOLS_INSTALL_DIR:PATH=bin \
    -DLLVM_INCLUDE_DOCS:BOOL=ON \
    -DLLVM_BUILD_DOCS:BOOL=ON \
    -DLLVM_ENABLE_SPHINX:BOOL=ON \
    -DLLVM_ENABLE_DOXYGEN:BOOL=OFF \
    -DLLVM_BUILD_LLVM_DYLIB:BOOL=ON \
    -DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
    -DLLVM_BUILD_EXTERNAL_COMPILER_RT:BOOL=ON \
    -DLLVM_INSTALL_TOOLCHAIN_ONLY:BOOL=OFF \
    -DLLVM_DEFAULT_TARGET_TRIPLE=${llvm_triple} \
    -DSPHINX_WARNINGS_AS_ERRORS=OFF \
    -DCMAKE_INSTALL_PREFIX=${_prefix} \
    -DLLVM_INSTALL_SPHINX_HTML_DIR=${_pkgdocdir}/html \
    -DSPHINX_EXECUTABLE=/usr/bin/sphinx-build-3

cmake --build llvm-build
cmake --install llvm-build