version: "3.8"
services:
    bb-worker:
        container_name: bb-worker-container
        build:
            context: ./
            dockerfile: ./Dockerfile.bb-worker
        environment:
            BUILDBOT_WORKER_NAME: standalone-build-x86_64
            BUILDBOT_INFO_ADMIN: kkleine@redhat.com
            # Upstream LLVM choices
            # lab.llvm.org:9994 = staging
            # lab.llvm.org:9990 = production
            BUILDBOT_MASTER: lab.llvm.org:9994
        volumes:
          - "./bb-worker/compose-secrets:/secret-volume:Z"